name = "Antique"
uuid = "be6e5d0e-34a5-4c8f-af83-e1b5389203d8"
authors = ["Shuhei Ohno"]
version = "0.9.0"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
SpecialFunctions = "2.3.1"
julia = "1.7"

[extras]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Suppressor", "Printf", "Markdown", "QuadGK", "Symbolics", "Latexify", "LaTeXStrings"]
